export const CommonConstant = {
    baseAPIURL: "https://localhost:7040/",
    userLoginURL: "api/Users/Login",
    rolesAPIURL: "api/Roles",
    rolesByOrgIdAPIURL: "api/Roles?organizationId=",
    searchRoleAPIURL: "gateway/roles/search?roleName=",
    rolesByIdAPIURL:"gateway/roles?id=",
    getUserTypesAPIURL:"gateway/usertypes",
    usersAPIURL:"api/Users",
    orgAPIURL:"api/Organizations",
    orgDeptAPIURL:"api/OrgDepartments",
    orgDeptByIdAPIURL:"api/OrgDepartments/GetById?id=",
    getOrgByIdAPIURL:"api/Organizations/GetById?id=",
    userDetailsById:"api/Users/userdetails?userId=",
    usersbyOrgIdAPIURL:"api/Users?orgId=",
    searchUsersAPIURL: "gateway/users/search",
    resetPasswordAPIURL:"gateway/users/resetpassword",
    studentDocumentsAPIURL:"gateway/studentdocuments",
    searchStudentDocumentsAPIURL:"gateway/studentdocuments/search?documentName=",
    departmentsByOrgId:"api/OrgDepartments/GetByOrgId?orgId=",
    courseAPIURL:"api/Courses",
    courseByIdAPIURL:"api/Courses/GetById?id=",
    guardianAPIURL:"api/Guardians",
    guardianByIdAPIURL:"api/Guardians/GetById?id=",
    studentAPIURL:"api/Students",
    getUpComingExams:"api/Students/GetUpComingExams",
    studentByIdAPIURL:"api/Students/GetById?id=",
    examAPIURL:"api/Exams",
    examByIdAPIURL:"api/Exams/GetById?id=",
    courseEnrollmentAPIURL:"api/CourseEnrollments",
    courseEnrollmentByIdAPIURL:"api/CourseEnrollments/GetById?id=",
    questionAPIURL:"api/Questions",
    questionByIdAPIURL:"api/Questions/GetById?id=",
    questionByExamIdAPIURL:"api/Questions/GetByExamId?id=",
    studentQuestionAttemptsAPIURL:"api/StudentQuestionAttempts",
    subjectAPIURL:"api/Subjects",
    subjectByIdAPIURL:"api/Subjects/GetById?id="
};
// export const CommonConstant = {
//     baseAPIURL: "https://localhost:7056/",//7213/",
//     userLoginURL: "api/Useres/login" //"gateway/login",
// };