export const HardCodedConstant = {
    Id: 'id',
    RoleName: 'roleName',
    Slash: '/',
    UserName: 'userName',
    Email: 'email',
    Password: 'password',
    UserID: 'userID',
    UserType: 'userType',
    Role: 'role',
    MobileNo: 'mobileNo',
    ModuleName: 'moduleName',
    Priority: 'priority',
    Range: 'range',
    MenuName: 'menuName',
    ModuleID: 'moduleID',
    MenuLevel: 'menuLevel',
    MenuParentID: 'menuParentID',
    MenuLinkPage: 'menuLinkPage',
    Status: 'status',
    Claims: 'claims',
    ViewAction: 'viewAction',
    NewAction: 'newAction',
    EditAction: 'editAction',
    DeleteAction: 'deleteAction',
    Country: 'country',
    State: 'state',
    District: 'district',
    MasterName:'masterName',
    FinYear:'finYear',
    FinStartDate:'finStartDate',
    FinEndDate:'finEndDate',
    BlockName:'blockName',
    StateID:'stateID',
    DistrictID:'districtID',
    Department:'department'
};